import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire,Module} from 'node:module';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import * as preview from '../lib/erasure-preview.ts';
function load(file,mocks={}){const path=new URL('../'+file,import.meta.url).pathname;const mod=new Module(path);mod.filename=path;mod.paths=Module._nodeModulePaths(new URL('../',import.meta.url).pathname);const require=createRequire(path);mod.require=id=>id in mocks?mocks[id]:require(id);mod._compile(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020}}).outputText,path);return mod.exports;}
const helpers=load('lib/erasure-lifecycle.ts',{'./erasure-preview':preview});
const dir='app/dashboard/[companyId]/retention/';
const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const ticket={preview_ticket_id:uuid(8),scope_kind:'candidate_record',candidate_count:1,counts:{'public.candidates':1},blockers:['execution_not_implemented'],policy_revision:1,resolution_revision:null,manifest_hash:'hash',schema_signature:'sig',generated_at:new Date().toISOString(),expires_at:new Date(Date.now()+300000).toISOString()};
const status={request_id:uuid(9),status:'authorized',generation:1,scope_kind:'candidate_record',candidate_count:1,created_at:new Date().toISOString(),cancelled_at:null,execution_enabled:false,phase:'local_frozen',blockers:['execution_not_implemented'],can_cancel:true};
function fixture(owner=true){const calls=[];const client={from(){return {select(){return this},eq(){return this},async maybeSingle(){return {data:{id:uuid(2)}}}}},async rpc(name,args){calls.push({name,args});return {data:name==='issue_candidate_erasure_preview'?ticket:name==='get_erasure_subject_resolution'?{id:uuid(6),owner_current:true}:uuid(9),error:null}}};const access={companyAccess:async()=>({client,company:{owner_id:uuid(1)},user:{id:owner?uuid(1):uuid(3)}})};const actions=load(dir+'actions.ts',{'../../../../lib/company-access':access,'../../../../lib/erasure-preview':preview,'../../../../lib/erasure-lifecycle':helpers});return {client,calls,actions,access};}
function form(){const f=new FormData();f.set('confirmed','on');f.set('request_key',uuid(4));f.set('preview_ticket_id',uuid(8));f.set('request_id',uuid(9));f.set('generation','1');f.set('scope_kind','candidate_record');return f;}
test('all lifecycle mutations require current company owner',async()=>{const f=fixture(false);assert.ok((await f.actions.issueErasureTicket(uuid(1),uuid(2),{},form())).error);for(const action of ['authorizeErasure','cancelErasure'])assert.ok((await f.actions[action](uuid(1),{},form())).error);assert.equal(f.calls.length,0)});
test('ticket uses server-resolved subject and route tenant candidate access',async()=>{const f=fixture(),data=form();data.set('scope_kind','confirmed_subject');data.set('resolution_id',uuid(999));assert.ok((await f.actions.issueErasureTicket(uuid(1),uuid(2),{},data)).ticket);assert.equal(f.calls[1].args.resolution_id,uuid(6));f.client.from=()=>({select(){return this},eq(){return this},async maybeSingle(){return {data:null}}});assert.ok((await f.actions.issueErasureTicket(uuid(1),uuid(2),{},data)).error);assert.equal(f.calls.length,2)});
test('authorization requires explicit confirmation and passes only DB ticket plus replay key',async()=>{const f=fixture(),data=form();data.delete('confirmed');assert.ok((await f.actions.authorizeErasure(uuid(1),{},data)).error);assert.equal(f.calls.length,0);data.set('confirmed','on');data.set('manifest_hash','forged');const result=await f.actions.authorizeErasure(uuid(1),{},data);assert.equal(result.requestId,uuid(9));assert.deepEqual(f.calls[0].args,{preview_ticket_id:uuid(8),request_key:uuid(4)});assert.match(result.saved,/Nie wykonano usunięcia/)});
test('cancellation works without candidate reads and passes expected generation',async()=>{const f=fixture();f.client.from=()=>{throw Error('candidate read forbidden')};const result=await f.actions.cancelErasure(uuid(1),{},form());assert.ok(result.saved);assert.deepEqual(f.calls[0].args,{target_request:uuid(9),expected_generation:1,request_key:uuid(4)});const data=form();data.set('generation','-1');assert.ok((await f.actions.cancelErasure(uuid(1),{},data)).error);assert.equal(f.calls.length,1)});
test('missing migration and stale ticket are errors without private DB detail',async()=>{const f=fixture();for(const code of ['PGRST202','PT409']){f.client.rpc=async()=>({data:null,error:{code,message:'PRIVATE'}});const result=await f.actions.authorizeErasure(uuid(1),{},form());assert.ok(result.error);assert.ok(!result.saved);assert.doesNotMatch(result.error,/PRIVATE/)}});
test('status parser fails closed for active execution and malformed lifecycle',()=>{assert.deepEqual(helpers.parseStatus(status),status);for(const change of [{execution_enabled:true},{phase:'erased'},{candidate_count:-1},{status:'cancelled',phase:'cancelled',can_cancel:true}])assert.throws(()=>helpers.parseStatus({...status,...change}));assert.throws(()=>helpers.parseTicket({...ticket,preview_ticket_id:'bad'}))});
function forms(mocks={}){return load(dir+'forms.tsx',{'./actions':{authorizeErasure(){},cancelErasure(){},issueErasureTicket(){}},'next/navigation':{useRouter:()=>({refresh(){}})},'../../../../lib/erasure-preview':preview,'../../../../lib/erasure-lifecycle':helpers,...mocks})}
test('UI displays freeze consent, expiry and no delete control',()=>{let i=0;const f=forms({'react':{...React,useActionState(){return [i++===0?{ticket}: {},()=>{},false]}}});const html=renderToStaticMarkup(React.createElement(f.ErasureAuthorization,{companyId:uuid(1),candidateId:uuid(2)}));assert.match(html,/Potwierdzam wskazany zakres/);assert.match(html,/Zatwierdź żądanie i wstrzymaj zmiany/);assert.match(html,/Wykonanie usunięcia nie jest jeszcze dostępne/);assert.match(html,/name="preview_ticket_id"/);assert.doesNotMatch(html,/Usuń teraz|Dane zostały usunięte/)});
test('stable key survives transport loss and cancel revision is unchanged',async()=>{const callbacks=[],received=[];const f=forms({'react':{...React,useActionState(cb){callbacks.push(cb);return [{},()=>{},false]}},'./actions':{async cancelErasure(_c,_s,data){received.push([data.get('request_key'),data.get('generation')]);throw Error('lost')}}});renderToStaticMarkup(React.createElement(f.CancelErasureForm,{companyId:uuid(1),request:status}));await callbacks[0]({},form());await callbacks[0]({},form());assert.deepEqual(received[0],received[1]);assert.equal(received[0][1],'1')});
test('status route fetches owner metadata without frozen candidate access',async()=>{const f=fixture();f.client.from=()=>{throw Error('candidate SELECT forbidden')};f.client.rpc=async(name,args)=>{f.calls.push({name,args});return {data:[status],error:null}};const page=load(dir+'page.tsx',{'next/link':{default:props=>React.createElement('a',props)},'next/navigation':{notFound(){throw Error('404')}},'./forms':{CancelErasureForm:()=>null},'../../../../lib/company-access':f.access,'../../../../lib/erasure-preview':preview,'../../../../lib/erasure-lifecycle':helpers});const html=renderToStaticMarkup(await page.default({params:Promise.resolve({companyId:uuid(1)}),searchParams:Promise.resolve({})}));assert.match(html,/Zatwierdzone — zmiany wstrzymane/);assert.equal(f.calls[0].name,'list_candidate_erasure_requests');assert.equal(f.calls[0].args.page_size,25)});
test('nonowner status page stops before metadata RPC',async()=>{const f=fixture(false);const page=load(dir+'page.tsx',{'next/link':{default:props=>React.createElement('a',props)},'next/navigation':{notFound(){throw Error('404')}},'./forms':{CancelErasureForm:()=>null},'../../../../lib/company-access':f.access,'../../../../lib/erasure-preview':preview,'../../../../lib/erasure-lifecycle':helpers});await assert.rejects(page.default({params:Promise.resolve({companyId:uuid(1)}),searchParams:Promise.resolve({})}),/404/);assert.equal(f.calls.length,0)});

test('authorization allows R3 execution blockers but rejects policy/schema blockers and ambiguous full person scope',()=>{
 for(const blocker of ['execution_not_implemented','external_inventory_unverified','backup_policy_unverified','administrative_inventory_pending_execution','subject_resolution_required'])assert.equal(helpers.canAuthorizeTicket({...ticket,blockers:[blocker]}),true,blocker);
 for(const blocker of ['retention_policy_required','schema_dependency_unknown','unknown_future_blocker'])assert.equal(helpers.canAuthorizeTicket({...ticket,blockers:[blocker]}),false,blocker);
 assert.equal(helpers.canAuthorizeTicket({...ticket,scope_kind:'confirmed_subject',blockers:['subject_resolution_required']}),false);
});
test('confirmed authorization leaves stale candidate page; unknown response does not navigate',()=>{
 for(const state of [{saved:'ok',requestId:uuid(9)},{error:'unknown response'}]){
  const effects=[],calls=[];let i=0;
  const f=forms({'react':{...React,useEffect(effect){effects.push(effect)},useActionState(){return [i++===0?{}:state,()=>{},false]}},'next/navigation':{useRouter:()=>({replace(path){calls.push(['replace',path])},refresh(){calls.push(['refresh'])}})}});
  renderToStaticMarkup(React.createElement(f.ErasureAuthorization,{companyId:uuid(1),candidateId:uuid(2)}));effects[0]();
  assert.deepEqual(calls,state.saved?[['replace',`/dashboard/${uuid(1)}/retention`],['refresh']]:[]);
 }
});
